CREATE TABLE IF NOT EXISTS complainttb (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  UserName TEXT NOT NULL,
  Location TEXT NOT NULL,
  ComplaintInfo TEXT NOT NULL,
  Image TEXT NOT NULL,
  Date TEXT NOT NULL,
  Status TEXT NOT NULL,
  Type TEXT NOT NULL,
  Ans TEXT NOT NULL,
  Image1 TEXT NOT NULL,
  OfficerName TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS officertb (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  Name TEXT NOT NULL,
  Mobile TEXT NOT NULL,
  Email TEXT NOT NULL,
  Address TEXT NOT NULL,
  Department TEXT NOT NULL,
  UserName TEXT NOT NULL,
  Password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS regtb (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  Name TEXT NOT NULL,
  Mobile TEXT NOT NULL,
  Email TEXT NOT NULL,
  Address TEXT NOT NULL,
  UserName TEXT NOT NULL,
  Password TEXT NOT NULL
);